#+title: Documentation de l'algorithme d'orientation COVID19

=Version: 20200330 (beta)=

** Introduction et contexte

Ce dépôt contient une présentation de l'algorithme d'orientation
COVID19 officiellement publié par le ministère des Solidarités et de
la Santé.

L'algorithme est défini par un comité scientifique, appelé CovidTélé,
réunissant des médecins et co-piloté par l'AP-HP et l'Institut
Pasteur.

Afin que toutes les initiatives qui participent à la gestion de la
crise sanitaire s'appuient sur les mêmes recommendations, le ministère
des Solidarités et de la Santé conseille la réutilisation de cet
algorithme.

Voir le [[https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/][site d'information générale]] produit à partir de ce dépôt.

** Document officiel

Le document officiel de l'algorithme d'orientation COVID19 est publié
par le ministère des Solidarités et de la Santé.  Il est [[https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/algorithme-orientation-covid19.html][lisible en
ligne]] et [[https://esante.gouv.fr/algorithme-orientation][téléchargeable ici]].

** Référencement

Toutes les applications d'information, d'orientation et de triage qui
réutilisent cet algorithme sont référencées sur le [[https://solidarites-sante.gouv.fr/soins-et-maladies/maladies/maladies-infectieuses/coronavirus/coronavirus-questions-reponses][site du ministère
des Solidarité et de la Santé]].

Si vous implémentez cet algorithme, renseignez [[http://www.sesam-vitale.fr/web/sesam-vitale/recensement-innovations-covid-19][ce formulaire en ligne]]
ou écrivez-nous à l'adresse =mobilisation-covid@sante.gouv.fr= pour que
votre initiative soit référencée.

Toute implémentation référencée doit 

1. respecter [[file:pseudo-code.org][l'algorithme d'orientation]] COVID19 ;
2. utiliser le [[https://github.com/Delegation-numerique-en-sante/covid19-algorithme-orientation/blob/master/docs/json/openapi3.json][schéma de données]] officiel ;
3. et suivre les recommandations d'[[file:implementation.org][implémentation]].

** Ce que contient ce dépôt

- des recommandations pour le [[file:referencement.org][référencement de votre application]] ;
- une présentation des [[file:pseudo-code.org][éléments formels de l'algorithme]] à respecter ;
- des exemples autour de [[file:implementation.org][son implémentation]] ;
- une [[file:preuve-formelle/][preuve formelle]] du fait que tous les cas possibles mènent à une conclusion ;
- le code source du [[https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/demonstrateur.html][démonstrateur]] de l'algorithme ;
- le code source d'une page web pour [[https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/repl.html][tester l'algorithme interactivement]].
- les instructions pour [[file:INSTALL.org][installer/développer]] à partir de ce dépôt.

** Contribuer

Les contributions sont les bienvenues, sous forme d'/issues/ ou de /pull
requests/.

** Licence

2020 Délégation ministérielle du numérique en santé et les contributeurs du dépôt.

Le code source de cette application est publié sous licence [[file:LICENSE][EPL 2.0]].


