#+title: Documentation de l'algorithme d'orientation COVID19

Version: 20200328 (beta)

** Introduction et contexte

Ce dépôt contient une présentation de l'algorithme d'orientation
COVID19 officiellement publié par le ministère des Solidarités et de
la Santé.

L'algorithme est défini par un comité scientifique, appelé CovidTélé,
réunissant des médecins et co-piloté par l'AP-HP et l'Institut
Pasteur.

Afin que toutes les initiatives qui participent à la gestion de la
crise sanitaire s'appuient sur les mêmes recommendations, le ministère
des Solidarités et de la Santé conseille la réutilisation de cet
algorithme.

Voir le [[https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/][site d'information générale]] produit à partir de ce dépôt.

** Ce que contient ce dépôt

- une présentation des [[file:pseudo-code.org][éléments formels de l'algorithme]] ;
- des recommandations sur [[file:implementation.org][son implémentation]] ;
- une [[file:preuve-formelle/][preuve formelle]] du fait que tous les cas possibles mènent à une conclusion ;
- le code source de la page statique de présentation de l'algorithme ;
- le code source d'un démonstrateur interactif de l'algorithme.

** Mettre à jour la [[https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/][page statique de présentation]]

- Éditez les fichiers [[file:website-contents.md][website-contents.md]] et [[file:website-meta.yml]].
- Lancez la commande =./build.sh=
- Committez, pushez.

** Mettre à jour le [[https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/demonstrateur.html][démonstrateur de l'algorithme]]

- Éditez le fichier [[file:config.yml]]
- Lancez la commande =./build.sh=
- Committez, pushez.

** Développer le [[https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/demonstrateur.html][démonstrateur de l'algorithme]] depuis ce dépôt

Pour développer le démonstrateur :

1. Configurez =config.yml=
2. Testez avec =clj -A:test-config=
3. Compilez avec =clj -A:fig=
4. Allez à [[http://localhost:9500]]
5. Éditez [[file:src/cljs/choices/core.cljs][core.cljs]]

Vous pouvez aussi lancer des exemples d'utilisation de l'algorithme :

: ~$ clj -m choices.algo

pour avoir un exemple ou 

: ~$ clj -m choices.algo 10

pour en avoir 10.

Les données affichées sont les paramètres des résultats d'une réponse
au questionnaire ainsi que la conclusion déduite de ces résultats.

Vous pouvez [[file:test/choices/algo.clj][lire le code]] avec lequel fonctionne ce test.

** Déployer les fichiers statiques depuis ce dépôt

Une seule commande :

: ./build.sh

** Contribuer

Les contributions sont les bienvenues, sous forme d'/issues/ ou de /pull
requests/.

** Réutilisations

L'algorithme est implémenté par [[maladiecoronavirus.fr][le site maladiecoronavirus.fr]].

Toutes les applications d'information, d'orientation et de triage qui
réutilisent cet algorithme sont référencées sur le [[https://solidarites-sante.gouv.fr/soins-et-maladies/maladies/maladies-infectieuses/coronavirus/coronavirus-questions-reponses][site du ministère
des Solidarité et de la Santé]].

Si vous implémentez cet algorithme, écrivez-nous à l'adresse
=mobilisation-covid@sante.gouv.fr= ou renseignez [[http://www.sesam-vitale.fr/web/sesam-vitale/recensement-innovations-covid-19][ce formulaire en ligne]]
pour que votre initiative soit référencée.

** Licence

2020 Délégation ministérielle du numérique en santé et les contributeurs du dépôt.

Le code source de cette application est publié sous licence [[file:LICENSE][EPL 2.0]].
