#+title: Documentation de l'algorithme d'orientation COVID19

Ce dépôt contient une présentation de l'algorithme d'orientation
COVID19 officiellement publié par le ministère des Solidarités et de la Santé.

L'algorithme est défini par un comité scientifique, appelé CovidTélé, réunissant des médecins et co-piloté par l'AP-HP et l'Institut Pasteur.

Afin que toutes les initiatives qui participent à la gestion de la crise sanitaire s'appuient sur les mêmes recommendations, le ministère des Solidarités et de la Santé conseille de s'appuie sur cet algorithme.

Voir le [[https://delegation-numerique-en-sante.github.io/covid19-algorithme-orientation/][site d'information générale]] produit à partir de ce dépôt.

Vous trouvez ici :

- une présentation des [[file:pseudo-code.org][éléments formels de l'algorithme]]
- des recommandations sur [[file:implementation.org][son implémentation]]
- une [[file:z3/][preuve formelle]] du fait que tous les cas possibles mènent à une conclusion
- des explications sur comment se servir de ce dépôt

* Mettre à jour le site

- Éditez les fichiers [[file:website-contents.md][website-contents.md]] et [[file:website-meta.yml]].
- Lancez la commande =./build.sh=
- Committez, pushez.

* Mettre à jour l'algorithme d'exemple en Clojure

- Éditez le fichier [[file:config.yml]]
- Lancez la commande =./build.sh=
- Committez, pushez.

* Développer l'application

Pour développer :

1. Configurez =config.yml=
2. Testez avec =clj -A:test=
3. Compilez avec =clj -A:fig=
4. Allez à http://localhost:9500

* Contributions

Les contributions sont les bienvenues, sous forme d'/issues/ ou de /pull
requests/.

* Réutilisations

L'algorithme est implémenté par [[maladiecoronavirus.fr][le site maladiecoronavirus.fr]].

Toutes les applications d'information, d'orientation et de triage qui réutilisent cet algorithme sont référencées sur le [[https://solidarites-sante.gouv.fr/soins-et-maladies/maladies/maladies-infectieuses/coronavirus/coronavirus-questions-reponses][site du ministère des Solidarité et de la Santé]]

Si vous implémentez cet algorithme, écrivez-nous à l'adresse mobilisation-covid@sante.gouv.fr pour que votre initiative soit 
référencée.

* Licence

2020 Délégation ministérielle du numérique en santé, Bastien Guerry et les contributeurs du dépôt.

Le code source de cette application est publié sous licence [[file:LICENSE][EPL 2.0]].
