Le présent algorithme a vocation à être utilisé par l’ensemble des
services numériques d’orientation des personnes mis en œuvre dans le
cadre de la crise sanitaire liée au Covid19.

Il a été élaboré par un comité d’experts, appelé CovidTélé, co-porté
par l’Institut Pasteur et l’Assistance publique des Hôpitaux de Paris.
Son contenu a été validé par le Ministère des Solidarités et de la
Santé.

Si vous réutilisez cet algorithme dans le cadre d’un service
d’information, d’orientation ou de triage, et que vous souhaitez que
votre initiative soit référencée par les pouvoirs publics, remplissez
ce formulaire.

FIXME: Lien à venir.

* Présentation de l’algorithme

L’algorithme est construit sur un questionnaire et un arbre de
décision.

Les réponses au questionnaire constituent un ensemble de données
utiles à des fins épidémiologiques. Les applications qui utilisent cet
algorithme peuvent remonter ces données au Health Data Hub (pour plus
d’information sur le sujet, contactez : xxx).

Ainsi, certaines questions du questionnaire n’entrent pas l’arbre de
décision.

L’arbre de décision est construit de façon séquentiel (i.e. les points
d'entrée ne sont pas des conditions mutuellement exclusives couvrant
toutes les réponses possibles, il faut traverser les conditions dans
l'ordre.).

* Questionnaire d’auto-évaluation

** Symptômes

FIXME: est-ce qu'une fièvre <= 35,4°C doit être considéré comme un
facteur de gravité mineur ?  Oui ci-dessous, non un peu plus bas.

- Pensez-vous avoir eu de la fièvre ces derniers jours (frissons,
  sueurs) ? OUI / NON / Ne sait pas

- Si oui : quelle est votre température ?
  - 35,5 - 37,7°C
  - 37,8 – 38,9°C = seuil retenu
  - >= 39°C ou <= 35,4°C => Facteur de gravité
  - Non renseignée & OUI à question précédente = fièvre présente.

- Avez-vous une toux ou une augmentation de votre toux habituelle ces
  derniers jours ? OUI / NON

- Avez-vous noté une forte diminution de votre gout ou de l’odorat ces
  derniers jours ? OUI / NON

- Avez-vous un mal de gorge ou des douleurs musculaires ou des
  courbatures inhabituelles apparus ces derniers jours ? OUI / NON

- Avez-vous de la diarrhée ces dernièrs 24 heures (au moins 3 selles
  molles) ? OUI / NON

- Avez-vous une fatigue inhabituelle ces derniers jours ? OUI / NON

- Si oui cette fatigue vous oblige-t-elle à vous reposer plus de la
  moitié de la journée ? OUI / NON => Facteur de gravité.

- Êtes-vous dans l'impossibilité de vous alimenter ou de boire DEPUIS
  24 HEURES OU PLUS ?  OUI / NON => Facteur de gravité.

- Dans les dernières 24 heures, avez-vous noté un manque de souffle
  INHABITUEL lorsque vous parlez ou faites un petit effort ? OUI / NON
  => Facteur de gravité.

** Facteur pronostique défavorable lié au terrain

- Quel est votre âge ?
  - < 15 ans : STOP : Prenez contact avec votre médecin généraliste au moindre doute. Cette application n’est pour l’instant pas adaptée aux personnes de moins de 15 ans. En cas d’urgence, appeler le 15.
  - >= 15 et < 50 ans
  - >= 50 et < 70 ans
  - >= 70 ans

- Quel est votre poids ? Quelle est votre taille ?
  - IMC >= 30 kg/m2 ou < 30 kg/m2

- Avez-vous de l’hypertension artérielle mal équilibrée ? Ou avez-vous une maladie cardiaque ou vasculaire ? Ou prenez-vous un traitement à visée cardiologique ? OUI / NON / Ne sait pas (= OUI).

- Êtes-vous diabétique ? OUI / NON

- Avez-vous ou avez-vous eu un cancer ? OUI / NON

- Avez-vous une maladie respiratoire ? Ou êtes-vous suivi par un pneumologue ? OUI / NON

- Avez-vous une insuffisance rénale chronique dialysée ? OUI / NON

- Avez-vous une maladie chronique du foie ? OUI / NON

- Êtes-vous enceinte ? OUI / NON / Non applicable

- Avez-vous une maladie connue pour diminuer vos défenses immunitaires OUI / NON / Ne sait pas (= NON)

- Prenez-vous un traitement immunosuppresseur ? C’est un traitement qui diminue vos défenses contre les infections. Voici quelques exemples : corticoïdes, méthotrexate, ciclosporine, tacrolimus, azathioprine, cyclophosphamide (liste non exhaustive). OUI / NON / Ne sait pas (= NON)

Considéré positif si au moins 1 item OUI ou en gras (âge, IMC).

- Entrée du code postal

** Facteurs de gravité

- Facteurs de gravité mineurs :
  - Fièvre > ou = 39°C
  - Fatigue : alitement > 50% du temps diurne

- Facteurs de gravité majeurs :
  - Gêne respiratoire
  - Difficultés importantes pour s’alimenter ou boire depuis plus de 24h
 

* Arbre de décision

** Patient avec fièvre, ou toux + mal de gorge, ou toux + trouble odorat ou fièvre + diarrhée :
 
*** Tout patient sans facteur pronostique

- Sans facteur de gravité & <50 ans : nous vous conseillons de rester à votre domicile et de contacter votre médecin en cas d’apparition de nouveaux symptômes. Vous pourrez aussi utiliser à nouveau l’application pour réévaluer vos symptômes.
- Sans facteur de gravité & 50-69 ans, ou avec au moins un facteur de gravité mineur : téléconsultation ou médecin généraliste ou visite à domicile (SOS médecins…)
 
*** Tout patient avec un facteur pronostique ou plus

- Aucun facteur de gravité : téléconsultation ou médecin généraliste ou visite à domicile
- Un seul facteur de gravité mineur : téléconsultation ou médecin généraliste ou visite à domicile
- les deux facteurs de gravité mineurs : CS MG ou téléCs et si pas possible de le joindre ou téléCS : faite le 15
 
** Tout patient avec ou sans facteur pronostique avec au moins un facteur de gravité majeur : Appel 15.
 
/Pour tout patient orienté vers une téléconsultation ou médecin généraliste : préciser “appelez le 15 si une gêne respiratoire ou des difficultés importantes pour s’alimenter ou boire pendant plus de 24h apparaissent.”/
 
*** Tout patient avec fièvre et toux :

*** Tout patient sans facteur pronostique :

- Sans facteur de gravité ou au moins 1 facteur de gravité mineur sans facteur de gravité majeur : téléconsultation ou médecin généraliste ou visite à domicile (SOS médecins…)
 
*** Tout patient avec un facteur pronostique ou plus :

- Aucun facteur de gravité : téléconsultation ou médecin généraliste ou visite à domicile
- Un seul facteur de gravité mineur : téléconsultation ou médecin généraliste ou visite à domicile
- Les deux facteurs de gravité mineurs : CS MG ou téléCs et si pas possible de le joindre ou téléCS : faite le 15
 
** Tout patient avec ou sans facteur pronostique avec au moins un facteur de gravité majeur : Appel 15.
 
** Tout patient avec un seul symptôme parmi fièvre, toux, mal de gorge, trouble de l’odorat

- Pas de facteur de gravité :
  - Votre situation ne relève probablement pas du Covid-19. Consultez votre médecin au moindre doute. Si de nouveaux symptômes apparaissent, refaites le test.

- Au moins un facteur de gravité ou un facteur pronostique :
  - Votre situation ne relève probablement pas du Covid-19. Un avis médical est recommandé. Au moindre doute, appelez le 15.
 
** Tout patient avec aucun symptôme

Votre situation ne relève probablement pas du Covid-19. N’hésitez pas à contacter votre médecin en cas de doute. Vous pouvez refaire le test en cas de nouveau symptôme pour réévaluer la situation. Pour toute information concernant le Covid-19, composer le 0 800 130 000.
 
Pour tous : Restez chez vous au maximum en attendant que les symptômes disparaissent. Prenez votre température deux fois par jour. Rappel des mesures d’hygiène.
 
Un dispositif national grand public de soutien psychologique au bénéfice des personnes qui en auraient besoin est accessible via le numéro vert : 0 800 130 000.
 
/Algorithme potentiellement modifiable après étude de cas et veille scientifique./
